/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.User;
import java.awt.CardLayout;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class FormJPanel extends javax.swing.JPanel {
    
    JPanel btmPanel ;
    ImageIcon scaledIcon;
    private File selectedFile;
    
        /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
    
    public FormJPanel(JPanel btmPanel){
        initComponents();
        this.btmPanel = btmPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilejLabel1 = new javax.swing.JLabel();
        namejLabel1 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        lastjLabel2 = new javax.swing.JLabel();
        lastjTextField2 = new javax.swing.JTextField();
        genderjLabel3 = new javax.swing.JLabel();
        genderComboBox1 = new javax.swing.JComboBox<>();
        agejLabel = new javax.swing.JLabel();
        agejTextField3 = new javax.swing.JTextField();
        phonejLabel5 = new javax.swing.JLabel();
        phonejTextField4 = new javax.swing.JTextField();
        mailjLabel6 = new javax.swing.JLabel();
        mailjTextField5 = new javax.swing.JTextField();
        hobbyLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea1 = new javax.swing.JTextArea();
        submitjButton2 = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        datejDateChooser1 = new com.toedter.calendar.JDateChooser();
        hobbyLabel8 = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        profilejLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        profilejLabel1.setForeground(new java.awt.Color(255, 255, 255));
        profilejLabel1.setText("New User Profile");

        namejLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        namejLabel1.setForeground(new java.awt.Color(255, 255, 255));
        namejLabel1.setText("First Name");

        lastjLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lastjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        lastjLabel2.setText("Last Name");

        genderjLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        genderjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        genderjLabel3.setText("Gender");

        genderComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        genderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox1.setSelectedIndex(-1);

        agejLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agejLabel.setForeground(new java.awt.Color(255, 255, 255));
        agejLabel.setText("Age");

        phonejLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        phonejLabel5.setForeground(new java.awt.Color(255, 255, 255));
        phonejLabel5.setText("Phone Number");

        phonejTextField4.setForeground(new java.awt.Color(102, 102, 102));

        mailjLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mailjLabel6.setForeground(new java.awt.Color(255, 255, 255));
        mailjLabel6.setText("Email");

        mailjTextField5.setForeground(new java.awt.Color(102, 102, 102));

        hobbyLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hobbyLabel7.setForeground(new java.awt.Color(255, 255, 255));
        hobbyLabel7.setText("Hobbies");

        hobbyTextArea1.setColumns(20);
        hobbyTextArea1.setRows(5);
        jScrollPane1.setViewportView(hobbyTextArea1);

        submitjButton2.setText("Submit profile");
        submitjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton2ActionPerformed(evt);
            }
        });

        imgLabel.setBackground(new java.awt.Color(102, 102, 102));

        datejDateChooser1.setDateFormatString("dd/MM/yyyy");

        hobbyLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hobbyLabel8.setForeground(new java.awt.Color(255, 255, 255));
        hobbyLabel8.setText("Date of Birth");

        uploadButton.setText("Upload Photo");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hobbyLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hobbyLabel8)
                                    .addComponent(mailjLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(profilejLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(mailjTextField5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(uploadButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(submitjButton2))
                                                .addComponent(datejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(namejLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastjLabel2)
                                            .addComponent(genderjLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(genderComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 226, Short.MAX_VALUE)
                                            .addComponent(lastjTextField2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(agejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(agejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phonejLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phonejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel1)
                            .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastjLabel2)
                            .addComponent(lastjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderjLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(agejLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(agejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonejLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailjLabel6)
                    .addComponent(mailjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hobbyLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbyLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitjButton2)
                    .addComponent(uploadButton))
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton2ActionPerformed

       try {
            User userObject = new User();
            Date selectedDate = datejDateChooser1.getDate();
      // 1. Get user details
            // Initialize the Objects
            userObject.setName(this.namejTextField1.getText());
            userObject.setLast(this.lastjTextField2.getText());
            userObject.setGender(this.genderComboBox1.getSelectedItem().toString());
            userObject.setAge(Integer.parseInt(this.agejTextField3.getText()));
            userObject.setPhone(this.phonejTextField4.getText());
            userObject.setMail(this.mailjTextField5.getText());
            userObject.setHobby(this.hobbyTextArea1.getText());
            userObject.setPhoto(selectedFile);
            userObject.setScaledIcon(this.scaledIcon);
       
            
            // Display result.
            System.out.println(userObject.getName());
            System.out.println(userObject.getLast());
            System.out.println(userObject.getGender());
            System.out.println(userObject.getAge());
            System.out.println(userObject.getPhone());
            System.out.println(userObject.getMail());
            System.out.println(userObject.getHobby());
            System.out.println(userObject.getPhoto());
            System.out.print(userObject);
            //System.out.println(userObject.getDob(selectedDate));

            // Validate Inputs
            if(userObject.getName().isBlank()) {
                JOptionPane.showMessageDialog(this, "Enter your First Name", "Wait!", HEIGHT);
                return;
            } else if (userObject.getLast().isBlank()) {
                JOptionPane.showMessageDialog(this, "Enter your Last Name", "Wait!", HEIGHT);
                return;
            } else if (userObject.getGender().isBlank()){
                JOptionPane.showMessageDialog(this, "Select Your Gender", "Wait!", HEIGHT);
                return;
            } else if (userObject.getPhone().isBlank()) {
                JOptionPane.showMessageDialog(this, "Enter your Phone Number", "Wait!", HEIGHT);
                return;
            } else if (userObject.getMail().isBlank()){
                JOptionPane.showMessageDialog(this, "Enter your e-mail", "Wait!", HEIGHT);
                return;
            } else if (userObject.getHobby().isBlank()) {
                JOptionPane.showMessageDialog(this, "Enter your Hobbies", "Wait!", HEIGHT);
                return;
            } else if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "Please select your Date of Birth", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (selectedFile == null) {  // Check if image is uploaded
                JOptionPane.showMessageDialog(this, "Please upload a photo before submitting.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } 

            userObject.setDob(selectedDate); 
            JOptionPane.showMessageDialog(this, userObject ,"Success!", HEIGHT,scaledIcon);
                           
          //Then navigate to View Form:
                     
                       ViewJPanel viewJPanelObject = new ViewJPanel(userObject);
                       this.btmPanel.add(viewJPanelObject);
                       CardLayout layout = (CardLayout) this.btmPanel.getLayout();
                       layout.next(btmPanel);
                        
                        //Pass Date to View Form

        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Please select your Gender", "Error!", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Please enter your Age", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitjButton2ActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser file = new JFileChooser();
                if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                   selectedFile = file.getSelectedFile();
                   try {
                        BufferedImage img = ImageIO.read(file.getSelectedFile());
                        Image edited_image = img.getScaledInstance(120, 150, Image.SCALE_SMOOTH);
                        if (edited_image != null) {
                            this.scaledIcon = new ImageIcon(edited_image);
                            imgLabel.setIcon(scaledIcon);
                         }
                        } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Please upload the image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                       } catch (NullPointerException npe) {
                    JOptionPane.showMessageDialog(this, "Please upload the image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                            }
    }//GEN-LAST:event_uploadButtonActionPerformed
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agejLabel;
    private javax.swing.JTextField agejTextField3;
    private com.toedter.calendar.JDateChooser datejDateChooser1;
    private javax.swing.JComboBox<String> genderComboBox1;
    private javax.swing.JLabel genderjLabel3;
    private javax.swing.JLabel hobbyLabel7;
    private javax.swing.JLabel hobbyLabel8;
    private javax.swing.JTextArea hobbyTextArea1;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastjLabel2;
    private javax.swing.JTextField lastjTextField2;
    private javax.swing.JLabel mailjLabel6;
    private javax.swing.JTextField mailjTextField5;
    private javax.swing.JLabel namejLabel1;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JLabel phonejLabel5;
    private javax.swing.JTextField phonejTextField4;
    private javax.swing.JLabel profilejLabel1;
    private javax.swing.JButton submitjButton2;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables

    
}
